# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Pipeline

on:
  push:
  pull_request:

jobs:
  SAST:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest

    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@master
          
      - name: Set up Snyk CLI to check for security issues
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: auth
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
      
      - name: Snyk Code test
        #run: snyk test --all-projects --org=aef0364d-d779-4277-a254-86c9a1273e6c
        run: snyk code test 
          
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif --severity-threshold=high
          
      #- name: Upload result to GitHub Code Scanning
      #  uses: github/codeql-action/upload-sarif@v3
      #  with:
      #    sarif_file: snyk.sarif
  UnitTest:
    runs-on: ubuntu-latest

    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Test
      # run: dotnet test tests/Core.Tests/Core.Tests.csproj --no-build --verbosity normal
      run: dotnet test tests/Core.Tests/Core.Tests.csproj --filter 'FullyQualifiedName!~Integration'
  
  build:
    runs-on: ubuntu-latest
    needs:
      - SAST
      - UnitTest

    if: github.event_name == 'push'   
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

  
  DeploySTG:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/Develop'

    steps:
    - uses: actions/checkout@v4
    - name: deploy
      run: echo 'Deploy STG'
      
  SmokeTesSTG:
    runs-on: ubuntu-latest
    needs: DeploySTG
    if: github.ref == 'refs/heads/Develop'
    
    steps:
    - uses: actions/checkout@v4
    - name: deploy
      run: echo 'Smoke Test STG'

  IntegrationTest:
    runs-on: ubuntu-latest
    needs: SmokeTesSTG
    if: github.ref == 'refs/heads/Develop'

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: TestIntegration
      run: dotnet test tests/Core.Tests/Core.Tests.csproj --filter 'Integration&FullyQualifiedName!~ErrorSimulation' --logger 'trx' --results-directory ./TestResults

  DeployPreProd:
    runs-on: ubuntu-latest
    needs: build
   
    if: github.ref == 'refs/heads/release'
    steps:
    - name: deploy
      run: echo 'Deploy PreProd'

  SmokeTestPreProd:
    runs-on: ubuntu-latest
    needs: DeployPreProd
    
    if: github.ref == 'refs/heads/release'
    steps:
    - name: deploy
      run: echo 'Smoke Test PreProd'

  FunctionalTest:
    runs-on: ubuntu-latest
    needs: SmokeTestPreProd

    if: github.ref == 'refs/heads/release'
    steps:
    - name: deploy
      run: echo 'FunctionalTest'

  DeployProd:
    runs-on: ubuntu-latest
    needs: build

    if: github.ref == 'refs/heads/main'
    steps:
    - name: deploy
      run: echo 'Deploy Prod'

  SmokeProd:
    runs-on: ubuntu-latest
    needs: DeployProd

    if: github.ref == 'refs/heads/main'
    steps:
    - name: deploy
      run: echo 'Smoke Test Prod'     